name: Daily Streak Update

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp
        run: echo 'Last updated: $(date -u)' > last-updated.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last-updated.txt
          git commit -m "📆 Daily streak update" || echo "No changes"
          git push

