name: YouTube Video Count

on:
  schedule:
    - cron: '0 */24 * * *'  # Every 24 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count YouTube Videos
        run: |
          LAST_DATE=$(tail -n 1 youtube/youtube-history.csv | cut -d',' -f1)
          awk -F',' -v d="$LAST_DATE" '$1==d{sum+=$3} END{print sum}' youtube/youtube-history.csv > docs/video-count.txt

      - name: Commit and push
        run: |
          git config --global user.name "uxillary"
          git config --global user.email "adam@ajstudios.dev"
          git add docs/video-count.txt
          git diff --cached --quiet || git commit -m "📺 Update video count"
          git push
