name: YouTube Video Count

on:
  schedule:
    - cron: '0 */24 * * *'  # Every 24 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count YouTube Videos
        run: |
          mkdir -p data
          CHANNELS=(
            "UCSBP35Fbo5Ka4XB4k1q8lAA:Main"
            "UCQ1vRrmmQtjAjWV1Xa0cCrg:Fortnite"
            "UClLdLKAF2G5M5zSmM3XMkOg:Troubleshooting"
            "UC5qhdHzN2qOhlgJ8XfqBEYg:Adamsmr"
            "UCtCdgJ40L_jdFUAZR2MiYzg:AJ_Studios"
          )

          TOTAL=0
          for entry in "${CHANNELS[@]}"; do
            IFS=":" read -r ID NAME <<< "$entry"
            COUNT=$(curl -s "https://www.googleapis.com/youtube/v3/channels?part=statistics&id=$ID&key=${{ secrets.YOUTUBE_API_KEY }}" | jq -r '.items[0].statistics.videoCount')
            TOTAL=$((TOTAL + COUNT))
          done

          echo "Total YouTube videos: $TOTAL" > data/video-count.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/video-count.txt
          git diff --cached --quiet || git commit -m "📺 Update video count"
          git push
