name: YouTube Video Count

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-video-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Get video counts
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          import json, requests, os

          API_KEY = os.environ["YOUTUBE_API_KEY"]

          channels = {
              "Main":         "UCSBP35Fbo5Ka4XB4k1q8lAA",
              "Fortnite":     "UCQ1vRrmmQtjAjWV1Xa0cCrg",
              "Troubleshooting": "UClLdLKAF2G5M5zSmM3XMkOg",
              "Adamsmr":      "UC5qhdHzN2qOhlgJ8XfqBEYg",
              "AJ_Studios":   "UCtCdgJ40L_jdFUAZR2MiYzg"
          }

          def get_uploads_playlist_id(channel_id):
              return "UU" + channel_id[2:]

          def get_video_count(playlist_id):
              total = 0
              page_token = ""
              while True:
                  url = f"https://www.googleapis.com/youtube/v3/playlistItems?part=id&playlistId={playlist_id}&maxResults=50&key={API_KEY}&pageToken={page_token}"
                  res = requests.get(url).json()
                  items = res.get("items", [])
                  total += len(items)
                  page_token = res.get("nextPageToken", "")
                  if not page_token:
                      break
              return total

          counts = {}
          for name, cid in channels.items():
              pid = get_uploads_playlist_id(cid)
              count = get_video_count(pid)
              counts[name] = count

          with open("youtube_video_count.json", "w") as f:
              json.dump(counts, f, indent=2)

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add youtube_video_count.json
          git commit -m "Update YouTube video counts" || echo "No changes to commit"
          git push
