name: XMR-BTC Price Tracker

on:
  schedule:
    - cron: '0 8,14,20 * * *'  # Every day at 08:00, 14:00, and 20:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch XMR and BTC Prices
        run: |
          mkdir -p xmr-btc docs

          DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          XMR=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=usd" | jq -r '.monero.usd')
          BTC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq -r '.bitcoin.usd')

          # Append to CSV history
          echo "$DATE,$XMR,$BTC" >> xmr-btc/history.csv

          # Write snapshot JSON
          echo "{
            \"date\": \"$DATE\",
            \"XMR\": \"$XMR\",
            \"BTC\": \"$BTC\"
          }" > xmr-btc/xmr-btc.json

      - name: Commit and push
        run: |
          git config --global user.name "uxillary"
          git config --global user.email "adamjch@proton.me"
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || true
          git add xmr-btc/history.csv xmr-btc/xmr-btc.json
          git commit -m "💱 XMR/BTC price update" || echo "No changes"
          git push
