name: XMR & BTC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Fetch BTC & XMR prices
        run: |
          DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          BTC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq -r '.bitcoin.usd')
          echo "[$DATE] BTC: $BTC USD" >> btc.txt

          XMR=$(curl -s https://api.coinpaprika.com/v1/tickers/xmr-monero | jq -r ".quotes.USD.price")
          echo "[$DATE] XMR: $XMR USD" >> xmr.txt

      - name: Commit and push price logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || true
          git add btc.txt xmr.txt
          git commit -m "📊 Logged BTC & XMR prices" || echo "No changes"
          git push
