name: YouTube Combined Stats (Summed)

on:
  schedule:
    - cron: '0 */24 * * *'  # Runs daily
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/youtube-summed.yml'
      - 'data/youtube/**'
      - 'docs/youtube/**'

permissions:
  contents: write

jobs:
  youtube_stats:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch YouTube stats and prepare snapshot
        env:
          API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          mkdir -p docs docs/youtube

          DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          HISTORY_FILE="docs/youtube/youtube-history-sum.csv"
          SNAPSHOT_FILE="docs/youtube-sum.json"

          if [ ! -f "$HISTORY_FILE" ]; then
            echo "date,channel,videos,subscribers,views" > "$HISTORY_FILE"
          fi

          echo "{" > "$SNAPSHOT_FILE"

          CHANNELS=( \
            "UCSBP35Fbo5Ka4XB4k1q8lAA:Main" \
            "UCQ1vRrmmQtjAjWV1Xa0cCrg:Fortnite" \
            "UClLdLKAF2G5M5zSmM3XMkOg:Troubleshooting" \
            "UC5qhdHzN2qOhlgJ8XfqBEYg:Adamsmr" \
            "UCtCdgJ40L_jdFUAZR2MiYzg:AJ_Studios" )

          total_subs=0
          total_videos=0
          total_views=0

          for entry in "${CHANNELS[@]}"; do
            IFS=":" read -r CHANNEL_ID LABEL <<< "$entry"
            STATS=$(curl -s "https://www.googleapis.com/youtube/v3/channels?part=statistics&id=$CHANNEL_ID&key=$API_KEY")
            SUBS=$(echo "$STATS" | jq -r '.items[0].statistics.subscriberCount')
            VIDEOS=$(echo "$STATS" | jq -r '.items[0].statistics.videoCount')
            VIEWS=$(echo "$STATS" | jq -r '.items[0].statistics.viewCount')

            echo "$DATE,$LABEL,$VIDEOS,$SUBS,$VIEWS" >> "$HISTORY_FILE"
            echo "  \"$LABEL\": { \"date\": \"$DATE\", \"videos\": $VIDEOS, \"subscribers\": $SUBS, \"views\": $VIEWS }," >> "$SNAPSHOT_FILE"

            total_subs=$((total_subs + SUBS))
            total_videos=$((total_videos + VIDEOS))
            total_views=$((total_views + VIEWS))
          done

          sed -i '$ s/,$//' "$SNAPSHOT_FILE"
          echo "}" >> "$SNAPSHOT_FILE"

          # Export totals to GitHub environment
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "TOTAL_SUBS=$total_subs" >> $GITHUB_ENV
          echo "TOTAL_VIDEOS=$total_videos" >> $GITHUB_ENV
          echo "TOTAL_VIEWS=$total_views" >> $GITHUB_ENV

      - name: Append to summed CSV
        run: |
          mkdir -p docs/youtube
          if [ ! -f "docs/youtube/youtube-history-summed.csv" ]; then
            echo "date,total_subscribers,total_videos,total_views" > docs/youtube/youtube-history-summed.csv
          fi

          echo "$DATE,$TOTAL_SUBS,$TOTAL_VIDEOS,$TOTAL_VIEWS" >> docs/youtube/youtube-history-summed.csv

      - name: Update total subscribers text
        run: echo "$TOTAL_SUBS" > total-subscribers.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || true
          git add docs/youtube/ docs/youtube-sum.json total-subscribers.txt
          git commit -m "📊 YouTube summed stats update (safe files)" || echo "No changes"
          git push
