name: Update YouTube Summed CSV

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read youtube.json and calculate totals
        id: calc
        run: |
          # Read JSON and sum using jq
          total_subs=$(jq '[.[] | .subscribers] | add' youtube.json)
          total_videos=$(jq '[.[] | .videos] | add' youtube.json)
          total_views=$(jq '[.[] | .views] | add' youtube.json)

          # Set GitHub Action outputs
          echo "total_subs=$total_subs" >> $GITHUB_ENV
          echo "total_videos=$total_videos" >> $GITHUB_ENV
          echo "total_views=$total_views" >> $GITHUB_ENV

      - name: Append new row to CSV
        run: |
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo "$DATE,$total_subs,$total_videos,$total_views" >> data/youtube/youtube-history-summed.csv

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/youtube/youtube-history-summed.csv
          git commit -m "Update YouTube history: $DATE"
          git push
